# 基础设置
baseurl = "https://hollson.github.io"      #默认发布到码云，推动Github请查看“deploy_github.sh”
title = "码夫庄园"
theme = "hollson"           #主题
languageCode = "zh-CN"                    #语言编码
defaultContentLanguage ="zh-CN"           #默认内容语言
disqusShortname = ""                      #评论功能
googleAnalytics = ""                      #谷歌分析
preserveTaxonomyNames = false             #标签转换，如："Hello world"转换成“hello-world`
paginate = 15                             #分页设置
paginatePath ="page"
hasCJKLanguage = true                     #检测是否包含中文/日文/韩文（会影响摘要和字数统计功能）
publishdir = "public_github"                     #静态页生成目录

# 构建输出 ["HTML", "RSS", "Algolia"]
[outputs]
home = ["HTML", "Algolia"]

# 首页设置
[params]
  header_image = "img/farm.jpg"
  SEOTitle = "专注于Golang、Docker、K8s、云计算等前沿技术"
  description = "。。。。。。。。。。。。。。。。。。。。"
  keyword = "Blog, Golang 博客, 个人网站, 互联网, Web, PaaS, Istio, Kubernetes, 微服务, Microservice"
  slogan = "提升码农亩产，掰直码农方向，授人以渔，功德无量，利在千秋 ."

  # image_404 = "img/404-bg.jpg"
  image_404 = "https://cdn.pixabay.com/photo/2016/08/06/18/45/adac-1574932_1280.jpg"
  title_404 = "你来到了没有知识的荒原 :("

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # 侧边栏设置
  sidebar_about_description = "一介码农，喜欢乐器、艺术、写博客,乐与大家分享经验"
  sidebar_avatar = "img/hollson.png"     

  featured_tags = true 
  featured_condition_size = 1


# 谷歌分析
  ba_track_id = ""
  

# 评论功能(国内无法访问，需要配置代理)
  # Follow https://github.com/mafool/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

# 开启功能
  reward = true            #打赏功能 
  reward_guide = "真诚赞赏，手留余香" 
  friends = true           #友情链接
  bookmarks = true         #书签功能
  about_me = true          #关于作者
  enableRobotsTXT =true    #创建robots.txt
  enableEmoji =true        #启用Emoji; see emoji-cheat-sheet.com
  archives=true            #显示归档
  omit_categories=false    #关闭分类导航吗 

  # Include any custom CSS and/or JS files, url or relative to /static folder
  custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

# 目录导航
  # [[params.addtional_menus]]
  # title =  "书籍"
  # href =  "/top/books/"
  [[params.addtional_menus]]
  title =  "关于"
  href =  "top/about/"

# 分类体系
# 分类体系（Taxonomies）表示作者对内容的一套或多套分类。比如标签（tags）、类目（categories）、归档（archives）等
[taxonomies]
    tag = "tags"
    category = "categories"
    archive = "archives"

# 文档路径
# /:monthname/:day/:weekday/:weekdayname/:yearday/:section/:title/:slug/:filename/
  [permalinks]
  post = "/:year/:month/:title/"


# 博客连接
  [params.social]
  github         = "https://github.com/hollson"
  wechat         = "/img/wechat_qrcode.jpeg"
  rss            = true 
  email          = "hollson@qq.com"
  linkedin       = "https://www.linkedin.com/in/hollson"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  #facebook      = "full profile url in facebook"
  #twitter       = "full profile url in twitter"
  #gitlab        = "full profile url in gitlab"

# 文件归档
# archives//


# 友情链接
  [[params.friend_link]]
  title = "Github博客"
  href =  "https://github.com/hollson"
  [[params.friend_link]]
  title = "CSDN博客"
  href =  "https://blog.csdn.net/gusand"
  [[params.friend_link]]
  title = "博客园"
  href =  "https://www.cnblogs.com/hollson/"
  [[params.friend_link]]
  title = "Hugo主页"
  href =  "https://gohugo.io/about/"
    

# 书签链接
  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesher"
  href =  "http://www.servicemesher.com"
  [[params.bookmark_link]]
  title =  "Pxhere"
  href = "https://pxhere.com"
  [[params.bookmark_link]]
  title = "Huabing"
  href = "https://zhaozhihan.com/"
  

# 啥玩意？
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 


[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
   [markup.highlight]
    style = "dracula"

