#!/bin/bash
echo -e "\033[0;32mDeploying updates to GitHub...\033[0m"

# 发布到Github
rm -rf ./public_github/*
hugo -v --baseURL=https://hollson.github.io -d public_github

cd public_github

git add .
msg="rebuilding site $(date)"
if [ $# -eq 1 ]; then
  msg="$1"
fi
git commit -m "$msg"
git push origin master
echo "【Github】项目发布成功！！！"
cd ..
