#!/bin/bash
echo -e "\033[0;32mDeploying updates to GitHub...\033[0m"

# 推送到远程仓库
git add .
msg="rebuilding site $(date)"
if [ $# -eq 1 ]; then
  msg="$1"
fi
git commit -m "$msg"
git push origin master
echo "源码推送成功！！！"
